name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-Go@v2
        
      - name: Build
        run: scripts/buildprod.sh
        jobs:

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: build docker
        run: gcloud builds submit --tag europe-central2-docker.pkg.dev/future-graph-442313-q0/notely-ar-repo/notely:latest .